// Export a recorded macro to popular automation formats so flows captured in
// ScrcpyGUI can be run by external tools.
//
//   * Maestro YAML  — https://maestro.mobile.dev (runnable as-is for
//     element-based steps; coordinate steps fall back to points).
//   * Appium Python — a driver-agnostic script skeleton the user wires their
//     own capabilities/driver into.
//
// Coordinate-only actions are inherently less portable than element-based
// ones, so those lines are emitted best-effort and annotated where a manual
// tweak is likely needed.

import type { ElementSelector, Macro, MacroStep } from '../types/macro'

/** Human-readable Android keycode names for the common keys we record. */
const KEYCODE_NAMES: Record<number, string> = {
  3: 'Home',
  4: 'Back',
  61: 'Tab',
  66: 'Enter',
  67: 'Delete',
  187: 'Recents',
}

function escapeDoubleQuotes(value: string): string {
  return value.replace(/\\/g, '\\\\').replace(/"/g, '\\"')
}

/** Pick the app id (package) to seed a Maestro flow, if any step captured one. */
function deriveAppId(steps: MacroStep[]): string | undefined {
  for (const s of steps) {
    if (
      (s.kind === 'tapElement' || s.kind === 'waitForElement') &&
      s.selector.package
    ) {
      return s.selector.package
    }
  }
  return undefined
}

// --- Maestro ----------------------------------------------------------------

function maestroSelectorBlock(sel: ElementSelector, indent: string): string {
  if (sel.resourceId)
    return `${indent}id: "${escapeDoubleQuotes(sel.resourceId)}"`
  if (sel.text) return `${indent}text: "${escapeDoubleQuotes(sel.text)}"`
  if (sel.contentDesc)
    return `${indent}text: "${escapeDoubleQuotes(sel.contentDesc)}"`
  if (sel.xpath)
    return `${indent}# xpath: ${sel.xpath} (map manually in Maestro)`
  return `${indent}# no stable selector captured`
}

export function toMaestroYaml(macro: Macro): string {
  const appId = deriveAppId(macro.steps) || 'your.app.package'
  const lines: string[] = []
  lines.push(`# Maestro flow generated by ScrcpyGUI — ${macro.name}`)
  lines.push(`appId: ${appId}`)
  lines.push('---')
  lines.push('- launchApp')

  for (const s of macro.steps) {
    switch (s.kind) {
      case 'tapElement':
        lines.push('- tapOn:')
        lines.push(maestroSelectorBlock(s.selector, '    '))
        break
      case 'tap':
        lines.push('- tapOn:')
        lines.push(`    point: "${s.x},${s.y}"`)
        break
      case 'swipe':
        lines.push('- swipe:')
        lines.push(`    start: "${s.x1},${s.y1}"`)
        lines.push(`    end: "${s.x2},${s.y2}"`)
        lines.push(`    duration: ${s.durationMs}`)
        break
      case 'text':
        lines.push(`- inputText: "${escapeDoubleQuotes(s.value)}"`)
        break
      case 'keyevent': {
        const name = KEYCODE_NAMES[s.keycode]
        if (name === 'Back' || name === 'Home' || name === 'Enter') {
          lines.push(`- pressKey: ${name}`)
        } else {
          lines.push(`# pressKey keycode ${s.keycode} (map manually)`)
        }
        break
      }
      case 'wait':
        lines.push('- waitForAnimationToEnd:')
        lines.push(`    timeout: ${s.ms}`)
        break
      case 'waitForElement':
        lines.push('- extendedWaitUntil:')
        lines.push('    visible:')
        lines.push(maestroSelectorBlock(s.selector, '      '))
        lines.push(`    timeout: ${s.timeoutMs}`)
        break
      case 'screenshot':
        lines.push(`- takeScreenshot: ${s.label || 'checkpoint'}`)
        break
      case 'launch':
        lines.push('- launchApp:')
        lines.push(`    appId: "${escapeDoubleQuotes(s.package)}"`)
        break
      case 'install':
        lines.push(`# installApp ${s.apkPath} (run "adb install" manually)`)
        break
      case 'command':
        lines.push(`# adb ${s.command} (no Maestro equivalent; run manually)`)
        break
      case 'recordScreen':
        lines.push(`- startRecording: ${s.label || 'recording'}`)
        lines.push(`# stopRecording after ~${s.seconds}s`)
        lines.push('- stopRecording')
        break
    }
  }

  return lines.join('\n') + '\n'
}

// --- Appium (Python) --------------------------------------------------------

function appiumLocator(
  sel: ElementSelector,
): { by: string; value: string } | null {
  if (sel.resourceId) return { by: 'AppiumBy.ID', value: sel.resourceId }
  if (sel.contentDesc)
    return { by: 'AppiumBy.ACCESSIBILITY_ID', value: sel.contentDesc }
  if (sel.text)
    return { by: 'AppiumBy.XPATH', value: `//*[@text="${sel.text}"]` }
  if (sel.xpath) return { by: 'AppiumBy.XPATH', value: sel.xpath }
  return null
}

function pyStr(value: string): string {
  return `"${escapeDoubleQuotes(value)}"`
}

export function toAppiumPython(macro: Macro): string {
  const lines: string[] = []
  lines.push(`# Appium script generated by ScrcpyGUI — ${macro.name}`)
  lines.push(
    '# Provide your own driver (desired capabilities) and pass it to run(driver).',
  )
  lines.push('import time')
  lines.push('from appium.webdriver.common.appiumby import AppiumBy')
  lines.push('from selenium.webdriver.support.ui import WebDriverWait')
  lines.push('from selenium.webdriver.support import expected_conditions as EC')
  lines.push('')
  lines.push('')
  lines.push('def run(driver):')

  const body: string[] = []
  for (const s of macro.steps) {
    switch (s.kind) {
      case 'tapElement': {
        const loc = appiumLocator(s.selector)
        if (loc) {
          body.push(
            `driver.find_element(${loc.by}, ${pyStr(loc.value)}).click()`,
          )
        } else {
          body.push(`driver.tap([(${s.x}, ${s.y})])  # no stable selector`)
        }
        break
      }
      case 'tap':
        body.push(`driver.tap([(${s.x}, ${s.y})])`)
        break
      case 'swipe':
        body.push(
          `driver.swipe(${s.x1}, ${s.y1}, ${s.x2}, ${s.y2}, ${s.durationMs})`,
        )
        break
      case 'text':
        body.push(
          `driver.switch_to.active_element.send_keys(${pyStr(s.value)})`,
        )
        break
      case 'keyevent':
        body.push(`driver.press_keycode(${s.keycode})`)
        break
      case 'wait':
        body.push(`time.sleep(${(s.ms / 1000).toFixed(2)})`)
        break
      case 'waitForElement': {
        const loc = appiumLocator(s.selector)
        const secs = (s.timeoutMs / 1000).toFixed(1)
        if (loc) {
          body.push(
            `WebDriverWait(driver, ${secs}).until(EC.presence_of_element_located((${loc.by}, ${pyStr(loc.value)})))`,
          )
        } else {
          body.push(`time.sleep(${secs})  # waitForElement: no stable selector`)
        }
        break
      }
      case 'screenshot':
        body.push(
          `driver.save_screenshot(${pyStr((s.label || 'checkpoint') + '.png')})`,
        )
        break
      case 'launch':
        body.push(`driver.activate_app(${pyStr(s.package)})`)
        break
      case 'install':
        body.push(`driver.install_app(${pyStr(s.apkPath)})`)
        break
      case 'command': {
        const tokens = s.command.trim().split(/\s+/).filter(Boolean)
        const args = tokens
          .slice(1)
          .map((tkn) => pyStr(tkn))
          .join(', ')
        body.push(
          `driver.execute_script("mobile: shell", {"command": ${pyStr(tokens[0] || '')}, "args": [${args}]})`,
        )
        break
      }
      case 'recordScreen':
        body.push('driver.start_recording_screen()')
        body.push(`time.sleep(${s.seconds})`)
        body.push(`driver.stop_recording_screen()  # base64 mp4`)
        break
    }
  }

  if (body.length === 0) body.push('pass')
  for (const line of body) lines.push(`    ${line}`)

  return lines.join('\n') + '\n'
}
