import { describe, expect, it } from 'vitest'
import { parseMaestroBuilderYaml } from './maestroBuilderParser'
import { buildMaestroBuilderYaml } from './maestroBuilderSerializer'
import { createEmptyMaestroFlow, createMaestroFlowAction } from './maestroBuilderFlow'
import type { MaestroFlow } from '../types/maestroBuilder'

describe('parseMaestroBuilderYaml', () => {
  it('parses the reference Payment Success Flow header and every action', () => {
    const yaml = [
      'appId: "com.laundryyou.washxpress.dev"',
      'tags:',
      '  - smoke',
      '  - payment',
      '---',
      '- launchApp:',
      '    stopApp: true',
      '- tapOn:',
      '    id: "scan_qr"',
      '- inputText: "WXP001"',
      '- tapOn:',
      '    id: "normal_wash"',
      '- assertVisible:',
      '    text: "Washer 01"',
      '- tapOn:',
      '    id: "confirm_payment"',
      '- assertVisible:',
      '    text: "Payment successful"',
      '- takeScreenshot: "payment_success"',
      '- pressKey: Home',
      '',
    ].join('\n')

    const flow = parseMaestroBuilderYaml(yaml)
    expect(flow.appId).toBe('com.laundryyou.washxpress.dev')
    expect(flow.tags).toEqual(['smoke', 'payment'])
    expect(flow.actions).toHaveLength(9)
    expect(flow.actions[0]).toMatchObject({ command: 'launchApp', config: { stopApp: true } })
    expect(flow.actions[1]).toMatchObject({ command: 'tapOn', selector: { type: 'id', value: 'scan_qr' } })
    expect(flow.actions[2]).toMatchObject({ command: 'inputText', config: { value: 'WXP001' } })
    expect(flow.actions[4]).toMatchObject({ command: 'assertVisible', selector: { type: 'text', value: 'Washer 01' } })
    expect(flow.actions[7]).toMatchObject({ command: 'takeScreenshot', config: { name: 'payment_success' } })
    expect(flow.actions[8]).toMatchObject({ command: 'pressKey', config: { key: 'Home' } })
  })

  it('round-trips flows generated by the serializer', () => {
    const original = createEmptyMaestroFlow('com.example.app', 'Round trip')
    original.tags = ['smoke']
    original.actions = [
      createMaestroFlowAction('launchApp'),
      { ...createMaestroFlowAction('tapOn'), selector: { type: 'id', value: 'confirm' } },
      { ...createMaestroFlowAction('waitFor'), selector: { type: 'text', value: 'Ready' }, config: { timeoutMs: 5000 } },
      { ...createMaestroFlowAction('setLocation'), config: { latitude: 13.75, longitude: 100.5 } },
    ]
    const yaml = buildMaestroBuilderYaml(original)
    const reparsed = parseMaestroBuilderYaml(yaml)
    const reserialized = buildMaestroBuilderYaml(reparsed)
    expect(reserialized).toBe(yaml)
  })

  it('preserves an unsupported command block verbatim instead of dropping it', () => {
    const yaml = [
      'appId: "com.example.app"',
      '---',
      '- launchApp',
      '- repeat:',
      '    times: 3',
      '    commands:',
      '      - tapOn: "Refresh"',
      '- back',
      '',
    ].join('\n')

    const flow: MaestroFlow = parseMaestroBuilderYaml(yaml)
    expect(flow.actions).toHaveLength(3)
    expect(flow.actions[1].command).toBe('__unsupported__')
    expect(String(flow.actions[1].config.raw)).toContain('repeat:')
    expect(String(flow.actions[1].config.raw)).toContain('tapOn: "Refresh"')

    const reserialized = buildMaestroBuilderYaml(flow)
    expect(reserialized).toContain('- repeat:\n    times: 3\n    commands:\n      - tapOn: "Refresh"')
  })
})
