import { describe, expect, it } from 'vitest'
import { parseMaestroBuilderYaml } from './maestroBuilderParser'
import { buildMaestroBuilderYaml } from './maestroBuilderSerializer'
import { createEmptyMaestroFlow, createMaestroFlowAction } from './maestroBuilderFlow'
import type { MaestroFlow } from '../types/maestroBuilder'

describe('parseMaestroBuilderYaml', () => {
  it('round-trips Maestro env variables into the visual model', () => {
    const parsed = parseMaestroBuilderYaml([
      'appId: "com.example.app"',
      'env:',
      '  username: "test@example.com"',
      '  password: "123456"',
      '---',
      '- launchApp',
      '',
    ].join('\n'))

    expect(parsed.variables?.map(({ name, value }) => ({ name, value }))).toEqual([
      { name: 'username', value: 'test@example.com' },
      { name: 'password', value: '123456' },
    ])
    expect(buildMaestroBuilderYaml(parsed)).toContain('env:\n  username: "test@example.com"')
  })
  it('parses the reference Payment Success Flow header and every action', () => {
    const yaml = [
      'appId: "com.laundryyou.washxpress.dev"',
      'tags:',
      '  - smoke',
      '  - payment',
      '---',
      '- launchApp:',
      '    stopApp: true',
      '- tapOn:',
      '    id: "scan_qr"',
      '- inputText: "WXP001"',
      '- tapOn:',
      '    id: "normal_wash"',
      '- assertVisible:',
      '    text: "Washer 01"',
      '- tapOn:',
      '    id: "confirm_payment"',
      '- assertVisible:',
      '    text: "Payment successful"',
      '- takeScreenshot: "payment_success"',
      '- pressKey: Home',
      '',
    ].join('\n')

    const flow = parseMaestroBuilderYaml(yaml)
    expect(flow.appId).toBe('com.laundryyou.washxpress.dev')
    expect(flow.tags).toEqual(['smoke', 'payment'])
    expect(flow.actions).toHaveLength(9)
    expect(flow.actions[0]).toMatchObject({ command: 'launchApp', config: { stopApp: true } })
    expect(flow.actions[1]).toMatchObject({ command: 'tapOn', selector: { type: 'id', value: 'scan_qr' } })
    expect(flow.actions[2]).toMatchObject({ command: 'inputText', config: { value: 'WXP001' } })
    expect(flow.actions[4]).toMatchObject({ command: 'assertVisible', selector: { type: 'text', value: 'Washer 01' } })
    expect(flow.actions[7]).toMatchObject({ command: 'takeScreenshot', config: { name: 'payment_success' } })
    expect(flow.actions[8]).toMatchObject({ command: 'pressKey', config: { key: 'Home' } })
  })

  it('round-trips flows generated by the serializer', () => {
    const original = createEmptyMaestroFlow('com.example.app', 'Round trip')
    original.tags = ['smoke']
    original.actions = [
      createMaestroFlowAction('launchApp'),
      { ...createMaestroFlowAction('tapOn'), selector: { type: 'id', value: 'confirm' } },
      { ...createMaestroFlowAction('waitFor'), selector: { type: 'text', value: 'Ready' }, config: { timeoutMs: 5000 } },
      { ...createMaestroFlowAction('setLocation'), config: { latitude: 13.75, longitude: 100.5 } },
    ]
    const yaml = buildMaestroBuilderYaml(original)
    const reparsed = parseMaestroBuilderYaml(yaml)
    const reserialized = buildMaestroBuilderYaml(reparsed)
    expect(reserialized).toBe(yaml)
  })

  it('preserves an unsupported command block verbatim instead of dropping it', () => {
    // `repeat` used to be the unsupported example here, but it's now a real
    // structured command (see the "parses a repeat block" test below) — use
    // a command still genuinely outside the registry's v1 scope instead.
    const yaml = [
      'appId: "com.example.app"',
      '---',
      '- launchApp',
      '- evalScript: ${output.value = 1}',
      '- back',
      '',
    ].join('\n')

    const flow: MaestroFlow = parseMaestroBuilderYaml(yaml)
    expect(flow.actions).toHaveLength(3)
    expect(flow.actions[1].command).toBe('__unsupported__')
    expect(String(flow.actions[1].config.raw)).toContain('evalScript:')

    const reserialized = buildMaestroBuilderYaml(flow)
    expect(reserialized).toContain('- evalScript: ${output.value = 1}')
  })

  it('parses a relational selector back into selector.relation/relatedValue', () => {
    const yaml = [
      'appId: "com.example.app"',
      '---',
      '- tapOn:',
      '    text: "Confirm payment"',
      '    below:',
      '      text: "Total"',
      '',
    ].join('\n')
    const flow = parseMaestroBuilderYaml(yaml)
    expect(flow.actions[0]).toMatchObject({
      command: 'tapOn',
      selector: { type: 'text', value: 'Confirm payment', relation: 'below', relatedValue: 'Total' },
    })
  })

  it('parses containsDescendants single-item list form', () => {
    const yaml = [
      'appId: "com.example.app"',
      '---',
      '- assertVisible:',
      '    id: "list_item"',
      '    containsDescendants:',
      '      - text: "Wireless Headphones"',
      '',
    ].join('\n')
    const flow = parseMaestroBuilderYaml(yaml)
    expect(flow.actions[0]).toMatchObject({
      command: 'assertVisible',
      selector: { type: 'id', value: 'list_item', relation: 'containsDescendants', relatedValue: 'Wireless Headphones' },
    })
  })

  it('round-trips a relational selector on the generic path, waitFor, and scrollUntilVisible', () => {
    const original = createEmptyMaestroFlow('com.example.app', 'Relational round trip')
    original.actions = [
      { ...createMaestroFlowAction('tapOn'), selector: { type: 'text', value: 'Confirm payment', relation: 'below', relatedValue: 'Total' } },
      {
        ...createMaestroFlowAction('waitFor'),
        selector: { type: 'text', value: 'Ready', relation: 'rightOf', relatedValue: 'Spinner' },
        config: { timeoutMs: 5000 },
      },
      {
        ...createMaestroFlowAction('scrollUntilVisible'),
        selector: { type: 'text', value: 'Terms', relation: 'childOf', relatedValue: 'footer' },
        config: { direction: 'DOWN', timeoutMs: 20_000 },
      },
    ]
    const yaml = buildMaestroBuilderYaml(original)
    const reparsed = parseMaestroBuilderYaml(yaml)
    const reserialized = buildMaestroBuilderYaml(reparsed)
    expect(reserialized).toBe(yaml)
    expect(reparsed.actions[0].selector).toMatchObject({ relation: 'below', relatedValue: 'Total' })
    expect(reparsed.actions[1].selector).toMatchObject({ relation: 'rightOf', relatedValue: 'Spinner' })
    expect(reparsed.actions[2].selector).toMatchObject({ relation: 'childOf', relatedValue: 'footer' })
  })

  it('parses a plain selector with no relation exactly as before (backward compatibility)', () => {
    const yaml = ['appId: "com.example.app"', '---', '- tapOn:', '    id: "confirm_payment"', ''].join('\n')
    const flow = parseMaestroBuilderYaml(yaml)
    expect(flow.actions[0].selector).toEqual({ type: 'id', value: 'confirm_payment' })
  })

  it('parses a repeat block into a structured action with real children', () => {
    const yaml = [
      'appId: "com.example.app"',
      '---',
      '- repeat:',
      '    times: 3',
      '    commands:',
      '      - tapOn:',
      '          text: "Refresh"',
      '      - assertVisible:',
      '          text: "Loaded"',
      '',
    ].join('\n')
    const flow = parseMaestroBuilderYaml(yaml)
    expect(flow.actions).toHaveLength(1)
    expect(flow.actions[0].command).toBe('repeat')
    expect(flow.actions[0].config).toMatchObject({ times: 3 })
    expect(flow.actions[0].children).toHaveLength(2)
    expect(flow.actions[0].children?.[0]).toMatchObject({ command: 'tapOn', selector: { type: 'text', value: 'Refresh' } })
    expect(flow.actions[0].children?.[1]).toMatchObject({ command: 'assertVisible', selector: { type: 'text', value: 'Loaded' } })
  })

  it('round-trips a repeat/retry containing multiple nested actions', () => {
    const original = createEmptyMaestroFlow('com.example.app', 'Nested round trip')
    original.actions = [
      {
        ...createMaestroFlowAction('repeat'),
        config: { times: 2 },
        children: [
          { ...createMaestroFlowAction('tapOn'), selector: { type: 'text', value: 'Refresh' } },
          { ...createMaestroFlowAction('assertVisible'), selector: { type: 'text', value: 'Loaded' } },
        ],
      },
      {
        ...createMaestroFlowAction('retry'),
        config: { maxRetries: 3 },
        children: [{ ...createMaestroFlowAction('inputText'), config: { value: 'hello' } }],
      },
    ]
    const yaml = buildMaestroBuilderYaml(original)
    const reparsed = parseMaestroBuilderYaml(yaml)
    const reserialized = buildMaestroBuilderYaml(reparsed)
    expect(reserialized).toBe(yaml)
    expect(reparsed.actions[0].children).toHaveLength(2)
    expect(reparsed.actions[1].children).toHaveLength(1)
  })

  it('still preserves a genuinely unknown command verbatim (regression guard)', () => {
    const yaml = [
      'appId: "com.example.app"',
      '---',
      '- someInventedFutureCommand:',
      '    withSomeField: 42',
      '- back',
      '',
    ].join('\n')
    const flow = parseMaestroBuilderYaml(yaml)
    expect(flow.actions).toHaveLength(2)
    expect(flow.actions[0].command).toBe('__unsupported__')
    expect(String(flow.actions[0].config.raw)).toContain('someInventedFutureCommand:')
    expect(flow.actions[1].command).toBe('back')
  })

  it('parses runFlow and runScript bare paths', () => {
    const yaml = [
      'appId: "com.example.app"',
      '---',
      '- runFlow: "subflows/login.yaml"',
      '- runScript: "scripts/setup.js"',
      '',
    ].join('\n')
    const flow = parseMaestroBuilderYaml(yaml)
    expect(flow.actions[0]).toMatchObject({ command: 'runFlow', config: { path: 'subflows/login.yaml' } })
    expect(flow.actions[1]).toMatchObject({ command: 'runScript', config: { path: 'scripts/setup.js' } })
  })
})
